[package]
name = "midi2kb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
active-win-pos-rs = "0.8.2"
device_query = "1.1.3"
eframe = "0.22.0"
egui = "0.22.0"
env_logger = "0.10.0"
midir = "0.9.1"
